apiVersion: v1
kind: Service
metadata:
  name: backend-data
  namespace: {{ .Values.namespace }}
  labels:
    app: comments-system
    tier: backend-data
spec:
  selector:
    app: comments-system
    tier: backend-data
  ports:
    - name: http
      port: {{ .Values.backendData.port }}
      targetPort: {{ .Values.backendData.port }}
