apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Values.namespace }}
  labels:
    app: comments-system
data:
  BACKEND_API_URL: "http://backend-api:{{ .Values.backendApi.port }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-api-config
  namespace: {{ .Values.namespace }}
  labels:
    app: comments-system
data:
  BACKEND_DATA_URL: "http://backend-data:{{ .Values.backendData.port }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-data-config
  namespace: {{ .Values.namespace }}
  labels:
    app: comments-system
data:
  DB_HOST: "db"
  DB_PORT: "{{ .Values.db.port }}"
  DB_NAME: "{{ .Values.db.database }}"
