apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: comments-system
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.storage.size }}
{{- if .Values.db.storage.storageClassName }}
  storageClassName: {{ .Values.db.storage.storageClassName }}
{{- end }}
