apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespace }}
  labels:
    app: comments-system
    tier: database
spec:
  selector:
    app: comments-system
    tier: database
  ports:
    - name: postgres
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
