{{- if .Values.frontend.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: comments-system
    tier: frontend
spec:
  to:
    kind: Service
    name: frontend
  port:
    targetPort: {{ .Values.frontend.port }}
{{- if .Values.frontend.route.host }}
  host: {{ .Values.frontend.route.host }}
{{- end }}
{{- end }}
