apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace }}
  labels:
    app: comments-system
type: Opaque
stringData:
  DB_USER: "{{ .Values.db.username }}"
  DB_PASSWORD: "{{ .Values.db.password }}"
