# Namespace for Helm deployments in OpenShift
namespace: darkblade-x-dev

replicaCount:
  frontend: 1
  backendApi: 1
  backendData: 1
  db: 1

image:
  frontend:
    repository: dpazmino6215/comments-frontend
    tag: latest
    pullPolicy: IfNotPresent
  backendApi:
    repository: dpazmino6215/comments-backend-api
    tag: latest
    pullPolicy: IfNotPresent
  backendData:
    repository: dpazmino6215/comments-backend-data
    tag: latest
    pullPolicy: IfNotPresent
  db:
    repository: postgres
    storageClassName: "gp3"
    tag: "15-alpine"
    pullPolicy: IfNotPresent

frontend:
  port: 8080
  route:
    enabled: true
    host: ""

backendApi:
  port: 8080

backendData:
  port: 8080

db:
  port: 5432
  database: comments
  username: comments
  password: changeme
  env:
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata
  volumeMounts:
    - name: db-storage
      mountPath: /var/lib/postgresql/data
  storage:
    size: 1Gi
    storageClassName: ""
